# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b88531a0ac8eb0b584f910d363511fa947afed666349b425875740f5de1241264bbda48d620ce51a9de710a239667ead7d908317d00cf7528494938abded968c

test:
  secret_key_base: ce1925ab3f809c9170b0d626f40dbac32e09e84ce5e03d94fa18e11ac72201c645904d85411f12430c75970f0f2ad23cc1c01f320dc860db6b4b7e413135be19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
